expansion:
  uspto:
    - /home/datalab/shreyasv/aizynthfinder/uspto_model.onnx
    - /home/datalab/shreyasv/aizynthfinder/uspto_templates.csv.gz
  ringbreaker:
    - /home/datalab/shreyasv/aizynthfinder/uspto_ringbreaker_model.onnx
    - /home/datalab/shreyasv/aizynthfinder/uspto_ringbreaker_templates.csv.gz     
filter:
  uspto: /home/datalab/shreyasv/aizynthfinder/uspto_filter_model.onnx
stock:
  zinc: /home/datalab/shreyasv/aizynthfinder/zinc_stock.hdf5
